apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: custom-allow-tcp-ssh-icmp
spec:
  allow:
    - protocol: tcp
      ports:
       - "22"
       - "3389"
    - protocol: icmp
  networkRef:
    name: custom-vpc
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: allow-internal 
spec:
  allow:
    - protocol: tcp
    - protocol: icmp
    - protocol: udp
  networkRef:
    name: custom-vpc
  sourceRanges:
    - "10.128.0.0/22"