apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: frontend
requires:
  - configs: ["adservice", "checkout", "currency", "products", "shoppingcart"]
profiles:
  - name: dev
    deploy:
      kubectl: {}
    manifests:
      kustomize:
        paths:
        - overlays/dev/
    verify:
    - name: verify-frontend
      container:
        name: frontend-test
        image: alpine:3.15.4
        command: ["/bin/sh"]
        args: ["-c","curl -o /dev/null http://store-dev.automateit.ca"]
  - name: stg
    deploy:
      kubectl: {}
    manifests:
      kustomize:
        paths:
        - overlays/stg/
    verify:
    - name: verify-frontend
      container:
        name: frontend-test
        image: alpine:3.15.4
        command: ["/bin/sh"]
        args: ["-c", "curl -o /dev/null  http://store-stg.automateit.ca"]
  - name: prod
    deploy:
      kubectl: {}
    manifests:
      kustomize:
        paths:
        - overlays/prod/
    verify:
    - name: verify-frontend
      container:
        name: frontend-test
        image: alpine:3.15.4
        command: ["/bin/sh"]
        args: ["-c","curl -o /dev/null  http://store.automateit.ca"]

