apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: frontend
requires:
  - configs: ["adservice", "checkout", "currency", "products", "shoppingcart"]
profiles:
  - name: dev
    deploy:
      kustomize:
        paths:
        - overlays/dev/
      statusCheck: true
    verify:
    - name: verify-frontend
      container:
        name: frontend-test
        image: alpine:3.15.4
        command: ["/bin/sh"]
        args: ["-c", "curl -s -o /dev/null -w "%{http_code}" http://store-dev.automateit.ca"]
  - name: stg
    deploy:
      kustomize:
        paths:
        - overlays/stg/
      statusCheck: true
    verify:
    - name: verify-frontend
      container:
        name: frontend-test
        image: alpine:3.15.4
        command: ["/bin/sh"]
        args: ["-c", "curl -s -o /dev/null -w "%{http_code}" http://store-stg.automateit.ca"]
  - name: prod
    deploy:
      kustomize:
        paths:
        - overlays/prod/
      statusCheck: true
    verify:
    - name: verify-frontend
      container:
        name: frontend-test
        image: alpine:3.15.4
        command: ["/bin/sh"]
        args: ["-c", "curl -s -o /dev/null -w "%{http_code}" http://store.automateit.ca"]

