apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    metadata:
      labels:
        app: frontend
  replicas: 1
  template:
    spec:
      containers:
        - name: frontend
