apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  annotations:
    external-dns.alpha.kubernetes.io/hostname: store-dev.automateit.ca.
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
