apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: redis-cartsvc
deploy:
  kubectl:
    manifests:
    - ./redis.yaml
---
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: shoppingcart
requires:
  - configs: [redis-cartsvc]
deploy:
  kubectl:
    manifests:
    - ./cartservice.yaml
