apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: swampup-2022-prod-cluster-noapproval
requireApproval: false
gke:
  cluster: projects/swampup-2022/locations/us-central1/clusters/prod-cluster