apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: swampup-2022-boutique-frontend
description: Online Boutique delivery pipeline
serialPipeline:
 stages:
 - targetId: swampup-2022-dev-cluster
   profiles:
   - dev
 - targetId: swampup-2022-stg-cluster
   profiles:
   - stg
 - targetId: swampup-2022-prod-cluster
   profiles:
   - prod