
pipelines:
  - name: deploy_adsvc_pipeline
    steps:
    - name: trigger_cloud_deploy
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            AD_SVC_IMAGE: ${res_adsvc_image_imageName}:${res_ad_svc_image_imageTag}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-online-boutique"
        integrations:        
          - name: artifactory
          - name: server_name
          - name: gcloud
        inputResources:
          - name: DeploymentRepo
          - name: adsvc_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline"
          - > 
           gcloud components update --quiet && gcloud components install beta --quiet
        onExecute:
          - >
           gcloud beta deploy releases create
           --delivery-pipeline $CD_PIPELINE
           --region $REGION
           --images $AD_SVC_IMAGE
           --source ../application-manifests/*