apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: checkout
deploy:
  kubectl:
    manifests:
    - ./checkoutservice.yaml
    - ./emailservice.yaml
    - ./paymentservice.yaml
    - ./shippingservice.yaml