
pipelines:
  - name: deploy_adservices_pipeline
    steps:
    - name: trigger_cloud_deploy_adservice
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            AD_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/adservice:${res_adsvc_build_info_buildNumber}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-ads"
        integrations:        
          - name: artifactory
          - name: gcloud
          - name: server_name
        inputResources:
          - name: adsvc_deployment_repo
          - name: adsvc_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline $CD_PIPELINE"
          - export REL_TIMESTAMP=$(date '+%Y%m%d-%H%S')
          - cd $res_adsvc_deployment_repo_resourcePath/online-boutique
          - > 
           gcloud components update --quiet 
        onExecute:
          - >
           gcloud deploy releases create adsvc-${REL_TIMESTAMP}  
           --delivery-pipeline $CD_PIPELINE
           --region $REGION
           --images=adservice=$AD_SVC_IMAGE
           --source application-manifests/ads/
  - name: deploy_checkoutservices_pipeline
    steps:
    - name: trigger_cloud_deploy_checkoutservices
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            CHECKOUT_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/checkoutservice:${res_checkoutsvc_build_info_buildNumber}
            EMAIL_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/emailservice:${res_emailsvc_build_info_buildNumber}
            PAYMENT_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/paymentservice:${res_paymentsvc_build_info_buildNumber}
            SHIPPING_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/shippingservice:${res_shippingsvc_build_info_buildNumber}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-checkout"
        integrations:        
          - name: artifactory
          - name: gcloud
          - name: server_name
        inputResources:
          - name: checkoutservices_deployment_repo
          - name: checkoutsvc_build_info
          - name: emailsvc_build_info
          - name: paymentsvc_build_info
          - name: shippingsvc_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline $CD_PIPELINE"
          - export REL_TIMESTAMP=$(date '+%Y%m%d-%H%S')
          - cd $res_checkoutservices_deployment_repo_resourcePath/online-boutique
          - > 
           gcloud components update --quiet 
        onExecute:
          - >
           gcloud deploy releases create checkoutsvc-${REL_TIMESTAMP} 
           --delivery-pipeline $CD_PIPELINE 
           --region $REGION 
           --images=checkoutservice=$CHECKOUT_SVC_IMAGE,emailservice=$EMAIL_SVC_IMAGE,paymentservice=$PAYMENT_SVC_IMAGE,shippingservice=$SHIPPING_SVC_IMAGE 
           --source application-manifests/checkout/
  - name: deploy_currencyservices_pipeline
    steps:
    - name: trigger_cloud_deploy_currencyservice
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            CURRENCY_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/currencyservice:${res_currencysvc_build_info_buildNumber}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-currency"
        integrations:        
          - name: artifactory
          - name: gcloud
          - name: server_name
        inputResources:
          - name: currencyservices_deployment_repo
          - name: currencysvc_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline $CD_PIPELINE"
          - export REL_TIMESTAMP=$(date '+%Y%m%d-%H%S')
          - cd $res_currencyservices_deployment_repo_resourcePath/online-boutique
          - > 
           gcloud components update --quiet 
        onExecute:
          - >
           gcloud deploy releases create currency-${REL_TIMESTAMP} 
           --delivery-pipeline $CD_PIPELINE 
           --region $REGION 
           --images=currencyservice=$CURRENCY_SVC_IMAGE 
           --source application-manifests/currency/
  - name: deploy_frontend_pipeline
    steps:
    - name: trigger_cloud_deploy_frontend
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            FRONTEND_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/frontend:${res_frontend_build_info_buildNumber}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-frontend"
        integrations:        
          - name: artifactory
          - name: gcloud
          - name: server_name
        inputResources:
          - name: frontendservices_deployment_repo
          - name: frontend_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline $CD_PIPELINE"
          - export REL_TIMESTAMP=$(date '+%Y%m%d-%H%S')
          - cd $res_frontendservices_deployment_repo_resourcePath/online-boutique
          - > 
           gcloud components update --quiet 
        onExecute:
          - >
           gcloud deploy releases create frontend-${REL_TIMESTAMP} 
           --delivery-pipeline $CD_PIPELINE 
           --region $REGION 
           --images=frontend=$FRONTEND_SVC_IMAGE 
           --source application-manifests/frontend/
  - name: deploy_productservices_pipeline
    steps:
    - name: trigger_cloud_deploy_productservices
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            PRODUCTCATALOG_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/productcatalogservice:${res_productcatalogsvc_build_info_buildNumber}
            RECOMMENDATION_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/recommendationservice:${res_recommendationsvc_build_info_buildNumber}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-products"
        integrations:        
          - name: artifactory
          - name: gcloud
          - name: server_name
        inputResources:
          - name: productservices_deployment_repo
          - name: productcatalogsvc_build_info
          - name: recommendationsvc_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline $CD_PIPELINE"
          - export REL_TIMESTAMP=$(date '+%Y%m%d%H%S')
          - cd $res_productservices_deployment_repo_resourcePath/online-boutique
          - > 
           gcloud components update --quiet 
        onExecute:
          - >
           gcloud deploy releases create productsvc-${REL_TIMESTAMP} 
           --delivery-pipeline $CD_PIPELINE 
           --region $REGION 
           --images=productcatalogservice=$PRODUCTCATALOG_SVC_IMAGE,recommendationservice=$RECOMMENDATION_SVC_IMAGE 
           --source application-manifests/products/
  - name: deploy_shoppingcartservices_pipeline
    steps:
    - name: trigger_cloud_deploy_shoppingcart
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            CART_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/cartservice:${res_cartsvc_build_info_buildNumber}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-shoppingcart"
        integrations:        
          - name: artifactory
          - name: gcloud
        inputResources:
          - name: shoppingcartservices_deployment_repo
          - name: cartsvc_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline $CD_PIPELINE"
          - export REL_TIMESTAMP=$(date '+%Y%m%d-%H%S')
          - cd $res_shoppingcartservices_deployment_repo_resourcePath/online-boutique
          - > 
           gcloud components update --quiet 
        onExecute:
          - >
           gcloud deploy releases create shoppingcart-${REL_TIMESTAMP} 
           --delivery-pipeline $CD_PIPELINE 
           --region $REGION 
           --images=cartservice=$CART_SVC_IMAGE 
           --source application-manifests/shoppingcart/
  - name: deploy_loadgenerator_pipeline
    steps:
    - name: trigger_cloud_deploy_loadgenerator
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            LOADGEN_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/loadgenerator:${res_loadgenerator_build_info_buildNumber}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-ads"
        integrations:        
          - name: artifactory
          - name: gcloud
          - name: server_name
        inputResources:
          - name: loadgeneratorservices_deployment_repo
          - name: loadgenerator_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline $CD_PIPELINE"
          - export REL_TIMESTAMP=$(date '+%Y%m%d-%H%S')
          - cd $res_loadgeneratorservices_deployment_repo_resourcePath/online-boutique
          - > 
           gcloud components update --quiet 
        onExecute:
          - >
           gcloud deploy releases create loadgenerator-${REL_TIMESTAMP} 
           --delivery-pipeline $CD_PIPELINE 
           --region $REGION 
           --images=loadgenerator=$LOADGEN_SVC_IMAGE 
           --source application-manifests/loadgenerator/


