apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    metadata:
      labels:
        app: frontend
  replicas: 4
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: 110m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 128Mi
