# resources:
#   - ../../base
# patches:
#   - target:
#       kind: Service
#       name: frontend-external
#     patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: frontend-external
#         annotations:
#           external-dns.alpha.kubernetes.io/hostname: store.automateit.ca.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - frontend.service-external.yaml
  - frontend.deployment.yaml
