
pipelines:
  - name: deploy_adservices_pipeline
    steps:
    - name: trigger_cloud_deploy_adservice
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            AD_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/adservice:${run_number}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-ads"
        integrations:        
          - name: artifactory
          - name: gcloud
          - name: server_name
        inputResources:
          - name: adsvc_deployment_repo
          - name: adsvc_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline"
          - > 
           gcloud components update --quiet && gcloud components install beta --quiet
        onExecute:
          - >
           gcloud beta deploy releases create adservices-release-${REL_TIMESTAMP}  
           --delivery-pipeline $CD_PIPELINE
           --region $REGION
           --images server=$AD_SVC_IMAGE
           --source ../application-manifests/ads/
  - name: deploy_checkoutservices_pipeline
    steps:
    - name: trigger_cloud_deploy_checkoutservices
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            CHECKOUT_SVC_IMAGE:  ${int_server_name_value}.jfrog.io/boutique/checkoutservice:${run_number}
            EMAIL_SVC_IMAGE:  ${int_server_name_value}.jfrog.io/boutique/emailservice:${run_number}
            PAYMENT_SVC_IMAGE:  ${int_server_name_value}.jfrog.io/boutique/paymentservice:${run_number}
            SHIPPING_SVC_IMAGE:  ${int_server_name_value}.jfrog.io/boutique/shippingservice:${run_number}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-checkout"
        integrations:        
          - name: artifactory
          - name: gcloud
          - name: server_name
        inputResources:
          - name: checkoutservices_deployment_repo
          - name: checkoutsvc_build_info
          - name: emailsvc_build_info
          - name: paymentsvc_build_info
          - name: shippingsvc_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline"
          - > 
           gcloud components update --quiet && gcloud components install beta --quiet
        onExecute:
          - >
           gcloud beta deploy releases create checkoutservices-release-${REL_TIMESTAMP} 
           --delivery-pipeline $CD_PIPELINE 
           --region $REGION 
           --images checkoutservice=$CHECKOUT_SVC_IMAGE,
           emailservice=$EMAIL_SVC_IMAGE,
           paymentservice=$PAYMENT_SVC_IMAGE,
           shippingservice=$SHIPPING_SVC_IMAGE 
           --source ../application-manifests/checkout/
  - name: deploy_currencyservices_pipeline
    steps:
    - name: trigger_cloud_deploy_currencyservice
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            CURRENCY_SVC: ${int_server_name_value}.jfrog.io/boutique/currencyservice:${run_number}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-currency"
        integrations:        
          - name: artifactory
          - name: gcloud
          - name: server_name
        inputResources:
          - name: currencyservices_deployment_repo
          - name: currencysvc_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline"
          - > 
           gcloud components update --quiet && gcloud components install beta --quiet
        onExecute:
          - >
           gcloud beta deploy releases create currency-release-${REL_TIMESTAMP} 
           --delivery-pipeline $CD_PIPELINE 
           --region $REGION 
           --images currencyservice=$CURRENCY_SVC_IMAGE 
           --source ../application-manifests/currency/
  - name: deploy_frontend_pipeline
    steps:
    - name: trigger_cloud_deploy
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            FRONTEND_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/frontend:${run_number}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-frontend"  
        integrations:        
          - name: artifactory
          - name: gcloud
          - name: server_name
        inputResources:
          - name: frontendservices_deployment_repo
          - name: frontend_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline"
          - > 
           gcloud components update --quiet && gcloud components install beta --quiet
        onExecute:
          - >
           gcloud beta deploy releases create frontend-release-${REL_TIMESTAMP} 
           --delivery-pipeline $CD_PIPELINE 
           --region $REGION 
           --images frontende=$FRONTEND_SVC_IMAGE 
           --source ../application-manifests/frontend/
  - name: deploy_productservicespipeline
    steps:
    - name: trigger_cloud_deploy
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            PRODUCTCATALOG_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/productcatalogservice:${run_number}
            RECOMMENDATION_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/recommendationservice:${run_number}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-products"
        integrations:        
          - name: artifactory
          - name: gcloud
          - name: server_name
        inputResources:
          - name: productservices_deployment_repo
          - name: productcatalogsvc_build_info
          - name: recommendationsvc_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline"
          - > 
           gcloud components update --quiet && gcloud components install beta --quiet
        onExecute:
          - >
           gcloud beta deploy releases create productservices-release-${REL_TIMESTAMP} 
           --delivery-pipeline $CD_PIPELINE 
           --region $REGION 
           --images productcatalogservice=$PRODUCTCATALOG_SVC_IMAGE,
           recommendationservice=$RECOMMENDATION_SVC_IMAGE 
           --source ../application-manifests/products/
  - name: deploy_shoppingcartservices_pipeline
    steps:
    - name: trigger_cloud_deploy
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            CART_SVC_IMAGE: ${res_cartsvc_build_info.docker.image.tag}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-shoppingcart"
        integrations:        
          - name: artifactory
          - name: gcloud
        inputResources:
          - name: shoppingcartservices_deployment_repo
          - name: cartsvc_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline"
          - > 
           gcloud components update --quiet && gcloud components install beta --quiet
        onExecute:
          - >
           gcloud beta deploy releases create shoppingcart-release-${REL_TIMESTAMP} 
           --delivery-pipeline $CD_PIPELINE 
           --region $REGION 
           --images cartservice=$CART_SVC_IMAGE 
           --source ../application-manifests/shoppingcart/ 
  - name: deploy_loadgenerator_pipeline
    steps:
    - name: trigger_cloud_deploy
      type: bash
      configuration:
        affinityGroup: fmkGroup
        environmentVariables:
            LOADGEN_SVC_IMAGE: ${int_server_name_value}.jfrog.io/boutique/loadgenerator:${run_number}
            REGION: "us-central1"
            CD_PIPELINE: "swampup-2022-boutique-ads"
        integrations:        
          - name: artifactory
          - name: gcloud
          - name: server_name
        inputResources:
          - name: loadgeneratorservices_deployment_repo
          - name: loadgenerator_build_info
      execution:
        onStart:
          - echo "Trigger Cloud Deploy Pipeline"
          - > 
           gcloud components update --quiet && gcloud components install beta --quiet
        onExecute:
          - >
           gcloud beta deploy releases create loadgenerator-release-${REL_TIMESTAMP} 
           --delivery-pipeline $CD_PIPELINE 
           --region $REGION 
           --images loadgenerator=$LOADGEN_SVC_IMAGE 
           --source ../application-manifests/loadgenerator/


