apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: frontend
requires:
  - configs: ["adservice", "checkout", "currency", "products", "shoppingcart"]
deploy:
  kubectl:
    manifests:
    - ./frontend.yaml
